### ISSUE TITLE
Vague readme

### ISSUE THREAD

**Issue by HamDerAndrew** [RyuLindow/Zagreus#1]
Readme is vague.

I suggest improving it 

<a href="https://emoji.gg/emoji/7455-pepenoted"><img src="https://cdn3.emoji.gg/emojis/7455-pepenoted.png" width="64px" height="64px" alt="pepenoted"></a>

**Comment by RyuLindow** [comment]
Hi @HamDerAndrew 

Thank you for the suggestion.

I have updated the readme.

Link to the commit - https://github.com/RyuLindow/Zagreus/commit/205ffc48eb572b4b0f50d06bde6dff77b7f9f36b

Please, don't stalk my GitHub. Thank you :)
